trigger ContentDocument_Trigger on ContentDocument (before Delete, after insert) {
    if(Trigger_Activation__c.getInstance('ContentDocument_Trigger').Active__c)
    {
        if(Trigger.isDelete)
        {
            if(Trigger.isBefore)
            {
                System.debug('In Before Trigger');
                list<ContentDocument> DocList =new list<ContentDocument>();
                for(ContentDocument con : Trigger.old) {
                    DocList.add(con);
                }    
                ContentDocumentTriggerManager.ContentDocument_before(DocList); 
                ContentDocumentTriggerManager.avoidDeleteFile(Trigger.oldMap);
            }
        }
        //When the File is Deleted    
        if(Trigger.isInsert) {
            if(Trigger.isAfter) {
                //ContentDocumentTriggerManager.documentAccessControl(Trigger.newMap);
            }
        }
    }
    
        //Added by Prachi --SSE-21436
   if(Trigger.isDelete && Trigger.isBefore){
            
                
              ContentDocumentTriggerManager.avoidDeleteAutoGeneratedPDF(Trigger.old,Trigger.oldMap);  
                        
        }
}