.picklist-container,

.lookup-container{

    width : 100%;

    margin: spacingNone;

}

.picklist-container .slds-dropdown,

.lookup-container .slds-dropdown{

    position: relative !important;

    z-index: 99 !important;

}

th.slds-has-focus, td.slds-has-focus{

    box-shadow: none !important;

}
.picklist-container .slds-scrollable_y,
.lookup-container .slds-scrollable_y {
    -webkit-overflow-scrolling: touch;
    max-height: 100%;
    overflow: hidden;
    overflow-y: hidden;
    height: 100%;
}