.tableCss table>thead .slds-th__action{
	background-color: rgb(243,243,243);
} 

.tableCss table>thead .slds-th__action:focus, .tableCss table> .slds-th__action:hover, .tableCss table>.slds-is-resizable .slds-th__action:focus, .tableCss table> .slds-is-resizable .tableCss table>.slds-th__action:focus:hover{
	background-color: rgb(243,243,243);
}

.datatable-CellColor{
  
  background-color:rgb(243,243,243);
}

.datatable-CellColor:hover{
  background-color:rgb(243,243,243)!important;
}

.tableCss table>thead .slds-resizable__divider  {display : none;}

